apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: mcp-server
  name: mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-fastapi-demo
  namespace: mcp-server
spec:
  selector:
    matchLabels:
      app: mcp-fastapi-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: mcp-fastapi-demo
    spec:
      containers:
        - name: simple-mcp-server
          imagePullPolicy: Always
          image: pfcurtis/simple-web-server:0.1.0

          ports:
          - containerPort: 8000
            name: mcp-server

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: mcp-server
  labels:
    app: mcp-fastapi-demo
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: mcp-fastapi-demo
